# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Digitalizando Cronicawan'
description:      'Documentación de los escritos en quechua del periódico Cronicawan de 1975'
url:              'https://runaqlib.github.io'
baseurl:          '/cronicawan-esp'
#copyright:        'Example copyright org, 2023'
logo:             '/assets/logo.png'
default_thumb:    '/assets/default.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude: ["Gemfile*", "*.gemspec", "Rakefile", "vendor", "spec", "README.md", "LICENSE.txt", "Docker*"]
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  transcriptions:
    output: true
    permalink: /:path/
  cronicawan: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'cronicawan_item' # the layout for the pages to use
    metadata:
      source: 'cronicawan-wax.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/cronicawan' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      cronicawan:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - creator
          - location
          - label
          - _date
          - object_type
          - edition
    

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: "Sobre"
    sub:
      - label: "Sobre Cronicawan"
        link: "/about-cronicawan/"
      - label: "Sobre el proyecto de digitalización"
        link: "/digitization-project/"
      - label: "Cómo utilizar el sitio"
        link: "/how-to-use/"
  - label: "Índice"
    link: "/index/"
  - label: "Explorar"
    link: "/collection/"
  - label: "Buscar"
    link: "/search/"
  - label: "View in English"
    link: "https://runaqlib.github.io/cronicawan-wax/"


# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/runaqlib-esp'
    - label: 'Créditos'
      link: '/credits'
  logos:
    - img: '/img/logo.png'

# FIN
